### ISSUE TITLE
Special character handling

### ISSUE THREAD

**Issue by bjarnerosendal** [patrickdemooij9/SimpleRedirects#38]
We have an Umbraco 13.5.2 site where we have setup this redirect entry:
![Screenshot 2024-11-05 145159](https://github.com/user-attachments/assets/28310fcc-cfdf-45a9-86b3-3b2d419a28a7)
Now, we are tried to get information about this redirect using the FindRedirect method.
This works fine, if we enter "aeldresagen" as oldUrl, but with the value set to "ældresagen", we cannot retrieve the redirect.
![Screenshot 2024-11-05 145130](https://github.com/user-attachments/assets/7299bada-1712-4c5a-be30-0d9322132bde)
Is there no support for special characters like this in SimpleRedirects or is it a configuration matter?

**Comment by patrickdemooij9** [comment]
Hi @bjarnerosendal 
I am actually quite surprised that the package still works on 13.5.2. Most of my time is currently spend on developing SeoToolkit: https://github.com/patrickdemooij9/SeoToolkit.Umbraco. Which also has a redirect module that is far superior than this one.

Though if you want to fork this one and fix the issue, it is because the url has to be url decoded before retrieving it from the database. (https://github.com/patrickdemooij9/SeoToolkit.Umbraco/commit/c46fb42e23eeffe630542ac5deb8749c3fb2e67e#diff-429989b92165f7e891f6daa26cb9ffbc39b78e69733ff16d47f29fb60595e379)

**Comment by bjarnerosendal** [comment]
Hi @patrickdemooij9 
Thank you for the quick reply and guiding my attention to SeoToolKit. We replaced SimpleRedirects with the SeoToolkit.Umbraco.Redirects and it works like a charm now! :)

**Comment by patrickdemooij9** [comment]
That is great to hear! If you ever have any feedback about it, make sure to let me know!
